services:
  react-prod:
    build:
      context: ./app_front-end
      dockerfile: ../Dockerfile
    image: trocskillhub-frontend
    ports:
      - "8099:8080"
    networks:
      - troc-network

networks:
  troc-network:
    external: true
    name: trocskillhub-network